### ISSUE TITLE
Work on Unity 5.4?

### ISSUE THREAD

**Issue by ma1onso** [rstals/Unity-SCORM-Integration-Kit#1]
Hi,
I'm working with Unity 5.4, but this not export to Web Player anymore...

**Comment by rstals** [comment]
Hi Alonso,

I just found out myself recently :(

I'm looking at seeing what can be done.  Possibly looking at re-factoring it to work with WebGL instead, but this requires removing the multi-threading from the code...

**Comment by ma1onso** [comment]
@rstals ok, thanks and waiting for the best decision

**Comment by rstals** [comment]
Hi,
I've updated the code to remove all multi-threading and added in a WebGL template for SCORM.
This package will now work with Unity 5 and WebGL.

**Comment by ma1onso** [comment]
Thanks @rstals

**Comment by Roy-Nelson-Tous** [comment]
i can't get it working for unity 2017

**Comment by Edebarudo** [comment]
Hi,
Thank you for an excellent plugin. I am currently working on exporting a old web player project to WebGL in Unity 5.6.4f1 and saw your comment above. I am replacing the old version of the UnityPackage with the new one right now, but it says that you haven't updated the plugin since 2015. Have you updated the UnityPackage, or is GitHub buggy? Can I get the new version that supports WebGL somewhere? Again, thank you for a great plugin!

**Comment by rstals** [comment]
Hi all,
I've updated the project to include a bunch of stuff for working with WebGL in the new versions of Unity3D.
Documentation is a bit out of date, but nothing has really changed in how you use it in your projects.
